/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic;

import basic.Collections3.Lists2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Lists2.lists2Run();
    }
}
