/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic;


import basic.interfaces.Dog;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Dog dog = new Dog("Fido", 3);
        System.out.println(dog.getAge());
        System.out.println(dog.name);
    }
}
