/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic;

import basic.Collections.Maps1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Maps1.maps1Run();
    }
}
